import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import '@/styles/globals.css';

import { cn } from '@/lib/utils';
import { Toaster } from 'sonner';

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'QuickLink',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={cn(
          'min-h-screen overflow-y-auto overflow-x-hidden bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <Toaster richColors expand={true} />

        <main className="mb-5">{children}</main>
      </body>
    </html>
  );
}
